"""Linear WRITE client: resolve an issue id, upload a PDF asset, post a comment.

Mirrors linear_client.py's auth/endpoint/POST style (raw API key in Authorization,
JSON {query, variables} to the GraphQL endpoint). Read tokens from os.environ.
Linear file attach is a two-step flow: `fileUpload` returns a signed S3 URL +
headers; PUT the bytes there; then reference the assetUrl in `commentCreate`.

SPIKE NOTE: validate the fileUpload->PUT->commentCreate sequence and the issue-id
resolver against the live API once before relying on it (see plan "Open risks").
"""
import os

import httpx

LINEAR_API = "https://api.linear.app/graphql"

_ISSUE_ID_QUERY = """
query($number: Float!, $teamKey: String!) {
  issues(filter: { number: { eq: $number }, team: { key: { eq: $teamKey } } }) {
    nodes { id identifier }
  }
}
"""

_FILE_UPLOAD = """
mutation($contentType: String!, $filename: String!, $size: Int!) {
  fileUpload(contentType: $contentType, filename: $filename, size: $size) {
    success
    uploadFile { uploadUrl assetUrl headers { key value } }
  }
}
"""

_COMMENT_CREATE = """
mutation($issueId: String!, $body: String!) {
  commentCreate(input: { issueId: $issueId, body: $body }) { success }
}
"""


def build_comment_markdown(ticket_key: str, report_url: str, score, verdict: str | None) -> str:
    score_txt = f"{score}" if score is not None else "n/a"
    verdict_txt = verdict or "see report"
    return (
        f"**QA Evidence — {ticket_key}**\n\n"
        f"- Verdict: **{verdict_txt}**\n"
        f"- Score: **{score_txt}**\n"
        f"- Full report: {report_url}\n\n"
        f"Evidence PDF attached above. Generated by SCRIBE auto-QA."
    )


def _headers(token: str) -> dict:
    return {"Authorization": token, "Content-Type": "application/json"}


async def resolve_issue_id(key: str, token: str) -> str | None:
    """INV-660 -> Linear issue UUID, via team-key + number filter."""
    try:
        team_key, num = key.split("-", 1)
        number = float(int(num))
    except Exception:
        return None
    try:
        async with httpx.AsyncClient(timeout=20) as client:
            resp = await client.post(LINEAR_API, headers=_headers(token), json={
                "query": _ISSUE_ID_QUERY,
                "variables": {"number": number, "teamKey": team_key},
            })
            if resp.status_code != 200:
                return None
            nodes = (((resp.json().get("data") or {}).get("issues") or {}).get("nodes") or [])
            return nodes[0]["id"] if nodes else None
    except Exception:
        return None


async def attach_evidence(ticket_key, pdf_path, comment_md, *, token, write_allowed):
    """Upload the PDF and post a comment. Gated; never raises."""
    if not write_allowed:
        return {"attached": False, "skipped_reason": "write permission off", "error": None}
    if not token:
        return {"attached": False, "skipped_reason": "no LINEAR_TOKEN", "error": None}
    if not os.path.exists(pdf_path):
        return {"attached": False, "skipped_reason": "pdf missing", "error": None}

    issue_id = await resolve_issue_id(ticket_key, token)
    if not issue_id:
        return {"attached": False, "skipped_reason": None, "error": f"could not resolve issue id for {ticket_key}"}

    try:
        data = open(pdf_path, "rb").read()
        filename = f"{ticket_key}-evidence.pdf"
        async with httpx.AsyncClient(timeout=60) as client:
            up = await client.post(LINEAR_API, headers=_headers(token), json={
                "query": _FILE_UPLOAD,
                "variables": {"contentType": "application/pdf", "filename": filename, "size": len(data)},
            })
            payload = (((up.json().get("data") or {}).get("fileUpload") or {}))
            uf = payload.get("uploadFile") or {}
            upload_url, asset_url = uf.get("uploadUrl"), uf.get("assetUrl")
            if not payload.get("success") or not upload_url or not asset_url:
                return {"attached": False, "skipped_reason": None, "error": "fileUpload failed"}

            put_headers = {h["key"]: h["value"] for h in (uf.get("headers") or [])}
            put_headers.setdefault("Content-Type", "application/pdf")
            put = await client.put(upload_url, headers=put_headers, content=data)
            if put.status_code not in (200, 201, 204):
                return {"attached": False, "skipped_reason": None, "error": f"asset PUT {put.status_code}"}

            body = f"[{ticket_key}-evidence.pdf]({asset_url})\n\n{comment_md}"
            cc = await client.post(LINEAR_API, headers=_headers(token), json={
                "query": _COMMENT_CREATE, "variables": {"issueId": issue_id, "body": body},
            })
            ok = (((cc.json().get("data") or {}).get("commentCreate") or {}).get("success"))
            if not ok:
                return {"attached": False, "skipped_reason": None, "error": "commentCreate failed"}
    except Exception as e:
        return {"attached": False, "skipped_reason": None, "error": str(e)}

    return {"attached": True, "skipped_reason": None, "error": None}
